export const brandData = [
  {
    name: "Apple",
    href: "/brands/apple",
    logo: "/brands/apple.png",
    categories: ["computers", "phones"],
  },
  {
    name: "Dell",
    href: "/brands/dell",
    logo: "/brands/dell.png",
    categories: ["computers", "monitors"],
  },
  {
    name: "HP",
    href: "/brands/hp",
    logo: "/brands/hp.png",
    categories: ["computers", "printers"],
  },
  {
    name: "Lenovo",
    href: "/brands/lenovo",
    logo: "/brands/lenovo.png",
    categories: ["computers"],
  },
  {
    name: "Asus",
    href: "/brands/asus",
    logo: "/brands/asus.png",
    categories: ["computers", "monitors", "routers"],
  },
  {
    name: "Acer",
    href: "/brands/acer",
    logo: "/brands/acer.png",
    categories: ["computers", "monitors"],
  },
  {
    name: "Samsung",
    href: "/brands/samsung",
    logo: "/brands/samsung.png",
    categories: ["phones", "monitors"],
  },
  {
    name: "Canon",
    href: "/brands/canon",
    logo: "/brands/canon.png",
    categories: ["printers"],
  },
  {
    name: "Epson",
    href: "/brands/epson",
    logo: "/brands/epson.png",
    categories: ["printers"],
  },
  {
    name: "Brother",
    href: "/brands/brother",
    logo: "/brands/brother.png",
    categories: ["printers"],
  },
  {
    name: "Google",
    href: "/brands/google",
    logo: "/brands/google.png",
    categories: ["phones", "routers"],
  },
  {
    name: "OnePlus",
    href: "/brands/oneplus",
    logo: "/brands/1plus.png",
    categories: ["phones"],
  },
  {
    name: "Xiaomi",
    href: "/brands/xiaomi",
    logo: "/brands/xiaomi.png",
    categories: ["phones"],
  },
  {
    name: "OPPO",
    href: "/brands/oppo",
    logo: "/brands/oppo.png",
    categories: ["phones"],
  },
  {
    name: "SpaceX",
    href: "/brands/spacex",
    logo: "/brands/spacex.png",
    categories: ["routers"],
  },
  {
    name: "TP-Link",
    href: "/brands/tp-link",
    logo: "/brands/tp-link.png",
    categories: ["routers"],
  },
  {
    name: "Netgear",
    href: "/brands/netgear",
    logo: "/brands/netgear.png",
    categories: ["routers"],
  },
  {
    name: "Linksys",
    href: "/brands/linksys",
    logo: "/brands/linksys.png",
    categories: ["routers"],
  },
  {
    name: "D-Link",
    href: "/brands/d-link",
    logo: "/brands/d-link.png",
    categories: ["routers"],
  },
  {
    name: "Mercusys",
    href: "/brands/mercusys",
    logo: "/brands/mercusys.png",
    categories: ["routers"],
  },
  {
    name: "Tenda",
    href: "/brands/tenda",
    logo: "/brands/tenda.png",
    categories: ["routers"],
  },
  {
    name: "Xerox",
    href: "/brands/xerox",
    logo: "/brands/xerox.png",
    categories: ["printers"],
  },
  {
    name: "Ricoh",
    href: "/brands/ricoh",
    logo: "/brands/ricoh.png",
    categories: ["printers"],
  },
  {
    name: "Pantum",
    href: "/brands/pantum",
    logo: "/brands/pantum.png",
    categories: ["printers"],
  },
  {
    name: "Kyocera",
    href: "/brands/kyocera",
    logo: "/brands/kyocera.png",
    categories: ["printers"],
  },
  {
    name: "JBL",
    href: "/brands/jbl",
    logo: "/brands/jbl.png",
    categories: ["speakers"],
  },
  {
    name: "Sony",
    href: "/brands/sony",
    logo: "/brands/sony.png",
    categories: ["speakers"],
  },
  {
    name: "Bose",
    href: "/brands/bose",
    logo: "/brands/bose.png",
    categories: ["speakers"],
  },
  {
    name: "Marshall",
    href: "/brands/marshall",
    logo: "/brands/marshall.png",
    categories: ["speakers"],
  },
  {
    name: "Ultimate Ears",
    href: "/brands/ultimate-ears",
    logo: "/brands/ultimate-ears.png",
    categories: ["speakers"],
  },
  {
    name: "Sonos",
    href: "/brands/sonos",
    logo: "/brands/sonos.png",
    categories: ["speakers"],
  },
  {
    name: "Anker",
    href: "/brands/anker",
    logo: "/brands/anker.png",
    categories: ["speakers"],
  },
  {
    name: "LG",
    href: "/brands/lg",
    logo: "/brands/lg.png",
    categories: ["speakers", "monitors"],
  },
  {
    name: "BenQ",
    href: "/brands/benq",
    logo: "/brands/benq.png",
    categories: ["monitors"],
  },
  {
    name: "MSI",
    href: "/brands/msi",
    logo: "/brands/msi.png",
    categories: ["monitors"],
  },
  {
    name: "Gigabyte",
    href: "/brands/gigabyte",
    logo: "/brands/gigabyte.png",
    categories: ["monitors"],
  },
];
